[package]
name = "my-hours"
version = "0.1.0"
edition = "2021"
authors = ["Joni Hasanen <joni@pieceofcode.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.13", features = ["derive"] }
directories-next = "2.0.0"
read_input = "0.8.6"
toml = "0.5.9"
serde = { version = "1.0.139", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["json"] }
serde_json = "1.0.82"
tokio = { version = "1.20.0", features = ["full"] }
chrono = { version = "0.4.19", features = ["serde"] }
sha2 = "0.10.2"
digest = "0.10.3"
comfy-table = "6.0.0"
