[package]
name = "my-hours"
version = "0.1.0"
edition = "2021"
authors = ["Joni Hasanen <joni@pieceofcode.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
directories-next = "2.0.0"
read_input = "0.8.6"
toml = "0.5.10"
serde = { version = "1.0.151", features = ["derive"] }
reqwest = { version = "0.11.13", features = ["json"] }
serde_json = "1.0.91"
tokio = { version = "1.23.0", features = ["full"] }
chrono = { version = "0.4.23", features = ["serde"] }
sha2 = "0.10.6"
digest = "0.10.6"
comfy-table = "6.1.3"
